package com.substring.auth.app.auth.controllers;
import com.substring.auth.app.auth.entities.*; import com.substring.auth.app.auth.payload.*; import com.substring.auth.app.auth.repositories.*; import com.substring.auth.app.auth.services.impl.*; import io.jsonwebtoken.JwtException; import jakarta.servlet.http.*; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.authentication.*; import org.springframework.security.core.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/v1/auth") @RequiredArgsConstructor public class AuthController{
 private final AuthenticationManager auth;private final UserRepository users;private final RefreshTokenRepository refresh;private final JwtService jwt;private final CookieService cookies;private final UserMapper mapper;private final AuthServiceImpl service;private final RateLimitService limiter;private final ClientInfoService client;private final EmailVerificationService verification;private final PasswordResetService reset;private final SessionService sessions;private final AuditLogService audit;@Value("${app.auth.email-verification-required:false}")boolean verificationRequired;
 @PostMapping("/register")public ResponseEntity<UserResponse> register(@Valid @RequestBody RegisterRequest r,HttpServletRequest q){limiter.checkRegister(client.ip(q));return ResponseEntity.status(201).body(service.register(r,client.ip(q),client.userAgent(q)));}
 @PostMapping("/login")public ResponseEntity<TokenResponse> login(@Valid @RequestBody LoginRequest r,HttpServletRequest q,HttpServletResponse s){String email=r.email().trim().toLowerCase();limiter.checkLogin(client.ip(q), email);try{auth.authenticate(new UsernamePasswordAuthenticationToken(email,r.password()));}catch(Exception e){limiter.recordLoginFailure(email);users.findByEmail(email).ifPresent(u->audit.record(u,"LOGIN_FAILED","Invalid credentials",client.ip(q),client.userAgent(q)));throw new BadCredentialsException("Invalid email or password");}User u=users.findByEmail(email).orElseThrow(()->new BadCredentialsException("Invalid email or password"));if(!u.isEnabled())throw new DisabledException("User account is disabled");if(verificationRequired&&u.getProvider()==Provider.LOCAL&&!u.isEmailVerified())throw new IllegalArgumentException("Please verify your email before signing in");limiter.clearLoginFailures(email);var pair=issue(u,q);cookies.attachRefreshCookie(s,pair.refresh,jwt.getRefreshTtlSeconds());cookies.addNoStoreHeaders(s);audit.record(u,"LOGIN_SUCCESS","Password login",client.ip(q),client.userAgent(q));return ResponseEntity.ok(TokenResponse.bearer(pair.access,jwt.getAccessTtlSeconds(),mapper.toResponse(u)));}
 @PostMapping("/refresh")@Transactional public ResponseEntity<TokenResponse> refresh(HttpServletRequest q,HttpServletResponse s){String raw=read(q).orElseThrow(()->new BadCredentialsException("Refresh token is missing"));try{if(!jwt.isRefreshToken(raw))throw new BadCredentialsException("Invalid refresh token");String jti=jwt.getJti(raw);UUID uid=jwt.getUserId(raw);var old=refresh.findByJtiForUpdate(jti).orElseThrow(()->new BadCredentialsException("Refresh token not recognized"));if(old.isRevoked()||old.getExpiresAt().isBefore(Instant.now())||!old.getUser().getId().equals(uid))throw new BadCredentialsException("Refresh token expired or revoked");old.setRevoked(true);String nextJti=UUID.randomUUID().toString();old.setReplacedByToken(nextJti);old.setLastUsedAt(Instant.now());refresh.save(old);var next=refresh.save(RefreshToken.builder().jti(nextJti).user(old.getUser()).createdAt(Instant.now()).expiresAt(Instant.now().plusSeconds(jwt.getRefreshTtlSeconds())).revoked(false).ipAddress(client.ip(q)).userAgent(client.userAgent(q)).build());String access=jwt.generateAccessToken(old.getUser());String rotated=jwt.generateRefreshToken(old.getUser(),next.getJti());cookies.attachRefreshCookie(s,rotated,jwt.getRefreshTtlSeconds());cookies.addNoStoreHeaders(s);audit.record(old.getUser(),"TOKEN_REFRESHED","Refresh token rotated",client.ip(q),client.userAgent(q));return ResponseEntity.ok(TokenResponse.bearer(access,jwt.getAccessTtlSeconds(),mapper.toResponse(old.getUser())));}catch(JwtException|IllegalArgumentException e){throw new BadCredentialsException("Invalid or expired refresh token");}}
 @PostMapping("/logout")public ResponseEntity<Void>logout(HttpServletRequest q,HttpServletResponse s){read(q).ifPresent(raw->{try{if(jwt.isRefreshToken(raw))refresh.findByJti(jwt.getJti(raw)).ifPresent(t->{t.setRevoked(true);refresh.save(t);audit.record(t.getUser(),"LOGOUT","Session revoked",client.ip(q),client.userAgent(q));});}catch(JwtException ignored){}});cookies.clearRefreshCookie(s);cookies.addNoStoreHeaders(s);SecurityContextHolder.clearContext();return ResponseEntity.noContent().build();}
 @PostMapping("/verify-email")public ResponseEntity<Void>verifyEmail(@RequestBody Map<String,String> b){String t=b.get("token");if(t==null||t.isBlank())throw new IllegalArgumentException("Verification token is required");verification.verify(t);return ResponseEntity.noContent().build();}
 @PostMapping("/forgot-password")public ResponseEntity<Void>forgot(@Valid @RequestBody EmailRequest r,HttpServletRequest q){limiter.checkForgotPassword(client.ip(q));reset.request(r.email());return ResponseEntity.accepted().build();}
 @GetMapping("/reset-password/validate")public ResponseEntity<Void>validateResetToken(@RequestParam String token){if(!reset.isValid(token))return ResponseEntity.status(HttpStatus.GONE).build();return ResponseEntity.noContent().build();}
 @PostMapping("/reset-password")public ResponseEntity<Void>reset(@Valid @RequestBody ResetPasswordRequest r){reset.reset(r.token(),r.newPassword());return ResponseEntity.noContent().build();}
 @GetMapping("/me")public ResponseEntity<UserResponse>me(Authentication a){return ResponseEntity.ok(mapper.toResponse(users.findByEmail(a.getName()).orElseThrow(()->new BadCredentialsException("User not found"))));}
 @GetMapping("/sessions")public ResponseEntity<List<SessionResponse>>sessions(Authentication a,HttpServletRequest q){User u=users.findByEmail(a.getName()).orElseThrow();String jti=read(q).map(x->{try{return jwt.getJti(x);}catch(Exception e){return "";}}).orElse("");return ResponseEntity.ok(sessions.list(u.getId(),jti));}
 @DeleteMapping("/sessions/{id}")public ResponseEntity<Void>revoke(Authentication a,@PathVariable UUID id){User u=users.findByEmail(a.getName()).orElseThrow();sessions.revoke(u.getId(),id);return ResponseEntity.noContent().build();}
 @GetMapping("/audit-log")public ResponseEntity<List<AuditLogResponse>>audit(Authentication a){User u=users.findByEmail(a.getName()).orElseThrow();return ResponseEntity.ok(audit.recent(u.getId()));}
 private TokenPair issue(User u,HttpServletRequest q){String jti=UUID.randomUUID().toString();refresh.save(RefreshToken.builder().jti(jti).user(u).createdAt(Instant.now()).expiresAt(Instant.now().plusSeconds(jwt.getRefreshTtlSeconds())).revoked(false).ipAddress(client.ip(q)).userAgent(client.userAgent(q)).build());return new TokenPair(jwt.generateAccessToken(u),jwt.generateRefreshToken(u,jti));}
 private Optional<String>read(HttpServletRequest q){if(q.getCookies()!=null){var c=Arrays.stream(q.getCookies()).filter(x->cookies.getRefreshTokenCookieName().equals(x.getName())).map(Cookie::getValue).filter(v->v!=null&&!v.isBlank()).findFirst();if(c.isPresent())return c;}String h=q.getHeader("X-Refresh-Token");if(h!=null&&!h.isBlank())return Optional.of(h.trim());String a=q.getHeader(HttpHeaders.AUTHORIZATION);if(a!=null&&a.regionMatches(true,0,"Bearer ",0,7))return Optional.of(a.substring(7).trim());return Optional.empty();}
 private record TokenPair(String access,String refresh){}
}
