package com.substring.auth.app.auth.services.impl;
import com.substring.auth.app.auth.entities.PasswordResetToken; import com.substring.auth.app.auth.repositories.*; import com.substring.auth.app.auth.services.EmailService; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.UUID;
@Service @RequiredArgsConstructor public class PasswordResetService{
 private final UserRepository users;private final PasswordResetTokenRepository repo;private final RefreshTokenRepository refresh;private final PasswordEncoder encoder;private final TokenHashService hasher;private final EmailService mail;private final AuditLogService audit;
 @Value("${app.auth.password-reset-minutes:15}")long resetMins;
 @Transactional public void request(String email){users.findByEmail(email.trim().toLowerCase()).ifPresent(u->{String raw=UUID.randomUUID()+"-"+UUID.randomUUID();repo.deleteByUserId(u.getId());repo.save(PasswordResetToken.builder().tokenHash(hasher.hash(raw)).user(u).expiresAt(Instant.now().plusSeconds(resetMins*60)).used(false).createdAt(Instant.now()).build());mail.sendPasswordResetEmail(u.getEmail(),u.getName(),raw);audit.record(u,"PASSWORD_RESET_REQUESTED","Password reset requested",null,null);});}
 public boolean isValid(String raw){if(raw==null||raw.isBlank())return false;return repo.findByTokenHash(hasher.hash(raw)).map(t->!t.isUsed()&&t.getExpiresAt().isAfter(Instant.now())).orElse(false);}
 @Transactional public void reset(String raw,String newPassword){var t=repo.findByTokenHash(hasher.hash(raw)).orElseThrow(()->new IllegalArgumentException("Invalid or expired reset token"));if(t.isUsed()||t.getExpiresAt().isBefore(Instant.now()))throw new IllegalArgumentException("Invalid or expired reset token");t.setUsed(true);t.getUser().setPassword(encoder.encode(newPassword));users.save(t.getUser());refresh.deleteByUserId(t.getUser().getId());audit.record(t.getUser(),"PASSWORD_RESET","Password reset completed; active sessions revoked",null,null);}
}
